// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/" | "/admin" | "/admin/journal" | "/admin/login" | "/admin/photos" | "/admin/site-images" | "/confidentialite" | "/contact" | "/experiences" | "/experiences/[slug]" | "/galerie" | "/journal" | "/journal/[slug]" | "/la-ferme" | "/mentions-legales" | "/privatiser-la-ferme"
type AppRouteHandlerRoutes = "/api/admin/articles" | "/api/admin/gallery" | "/api/admin/login" | "/api/admin/logout" | "/api/admin/site-images" | "/api/admin/upload"
type PageRoutes = never
type LayoutRoutes = "/" | "/admin"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes | AppRouteHandlerRoutes


interface ParamMap {
  "/": {}
  "/admin": {}
  "/admin/journal": {}
  "/admin/login": {}
  "/admin/photos": {}
  "/admin/site-images": {}
  "/api/admin/articles": {}
  "/api/admin/gallery": {}
  "/api/admin/login": {}
  "/api/admin/logout": {}
  "/api/admin/site-images": {}
  "/api/admin/upload": {}
  "/confidentialite": {}
  "/contact": {}
  "/experiences": {}
  "/experiences/[slug]": { "slug": string; }
  "/galerie": {}
  "/journal": {}
  "/journal/[slug]": { "slug": string; }
  "/la-ferme": {}
  "/mentions-legales": {}
  "/privatiser-la-ferme": {}
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/": never
  "/admin": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap, AppRouteHandlerRoutes }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }

  /**
   * Context for Next.js App Router route handlers
   * @example
   * ```tsx
   * export async function GET(request: NextRequest, context: RouteContext<'/api/users/[id]'>) {
   *   const { id } = await context.params
   *   return Response.json({ id })
   * }
   * ```
   */
  interface RouteContext<AppRouteHandlerRoute extends AppRouteHandlerRoutes> {
    params: Promise<ParamMap[AppRouteHandlerRoute]>
  }
}
