// This file is generated automatically by Next.js
// Do not edit this file manually
// This file validates that all pages and layouts export the correct types

import type { AppRoutes, LayoutRoutes, ParamMap, AppRouteHandlerRoutes } from "./routes.js"
import type { ResolvingMetadata, ResolvingViewport } from "next/types.js"
import type { NextRequest } from 'next/server.js'

type AppPageConfig<Route extends AppRoutes = AppRoutes> = {
  default: React.ComponentType<{ params: Promise<ParamMap[Route]> } & any> | ((props: { params: Promise<ParamMap[Route]> } & any) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type LayoutConfig<Route extends LayoutRoutes = LayoutRoutes> = {
  default: React.ComponentType<LayoutProps<Route>> | ((props: LayoutProps<Route>) => React.ReactNode | Promise<React.ReactNode> | never | void | Promise<void>)
  generateStaticParams?: (props: { params: ParamMap[Route] }) => Promise<any[]> | any[]
  generateMetadata?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingMetadata
  ) => Promise<any> | any
  generateViewport?: (
    props: { params: Promise<ParamMap[Route]> } & any,
    parent: ResolvingViewport
  ) => Promise<any> | any
  metadata?: any
  viewport?: any
}

type RouteHandlerConfig<Route extends AppRouteHandlerRoutes = AppRouteHandlerRoutes> = {
  GET?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  POST?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PUT?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  PATCH?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  DELETE?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  HEAD?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
  OPTIONS?: (request: NextRequest, context: { params: Promise<ParamMap[Route]> }) => Promise<Response | void> | Response | void
}


// Validate ../../app/admin/journal/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/journal">> = Specific
  const handler = {} as typeof import("../../app/admin/journal/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/login/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/login">> = Specific
  const handler = {} as typeof import("../../app/admin/login/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../app/admin/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/photos/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/photos">> = Specific
  const handler = {} as typeof import("../../app/admin/photos/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/admin/site-images/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/admin/site-images">> = Specific
  const handler = {} as typeof import("../../app/admin/site-images/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/confidentialite/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/confidentialite">> = Specific
  const handler = {} as typeof import("../../app/confidentialite/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/contact/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/contact">> = Specific
  const handler = {} as typeof import("../../app/contact/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/experiences/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/experiences/[slug]">> = Specific
  const handler = {} as typeof import("../../app/experiences/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/experiences/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/experiences">> = Specific
  const handler = {} as typeof import("../../app/experiences/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/galerie/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/galerie">> = Specific
  const handler = {} as typeof import("../../app/galerie/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/journal/[slug]/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/journal/[slug]">> = Specific
  const handler = {} as typeof import("../../app/journal/[slug]/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/journal/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/journal">> = Specific
  const handler = {} as typeof import("../../app/journal/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/la-ferme/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/la-ferme">> = Specific
  const handler = {} as typeof import("../../app/la-ferme/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/mentions-legales/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/mentions-legales">> = Specific
  const handler = {} as typeof import("../../app/mentions-legales/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/privatiser-la-ferme/page.tsx
{
  type __IsExpected<Specific extends AppPageConfig<"/privatiser-la-ferme">> = Specific
  const handler = {} as typeof import("../../app/privatiser-la-ferme/page.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/articles/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/articles">> = Specific
  const handler = {} as typeof import("../../app/api/admin/articles/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/gallery/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/gallery">> = Specific
  const handler = {} as typeof import("../../app/api/admin/gallery/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/login/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/login">> = Specific
  const handler = {} as typeof import("../../app/api/admin/login/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/logout/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/logout">> = Specific
  const handler = {} as typeof import("../../app/api/admin/logout/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/site-images/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/site-images">> = Specific
  const handler = {} as typeof import("../../app/api/admin/site-images/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/api/admin/upload/route.ts
{
  type __IsExpected<Specific extends RouteHandlerConfig<"/api/admin/upload">> = Specific
  const handler = {} as typeof import("../../app/api/admin/upload/route.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}





// Validate ../../app/admin/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/admin">> = Specific
  const handler = {} as typeof import("../../app/admin/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}

// Validate ../../app/layout.tsx
{
  type __IsExpected<Specific extends LayoutConfig<"/">> = Specific
  const handler = {} as typeof import("../../app/layout.js")
  type __Check = __IsExpected<typeof handler>
  // @ts-ignore
  type __Unused = __Check
}
